version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./notes.db
