services:
  mongodb:
    image: mongo:6.0
    container_name: liquor-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: liquor_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
