# Generated by Django 4.2.30 on 2026-05-24 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='赏析标题')),
                ('content', models.TextField(verbose_name='赏析内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='赏析作者')),
            ],
            options={
                'verbose_name': '诗词赏析',
                'verbose_name_plural': '诗词赏析',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '诗词分类',
                'verbose_name_plural': '诗词分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='诗词标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('dynasty', models.CharField(choices=[('先秦', '先秦'), ('汉', '汉'), ('魏晋', '魏晋'), ('南北朝', '南北朝'), ('唐', '唐'), ('宋', '宋'), ('元', '元'), ('明', '明'), ('清', '清'), ('近现代', '近现代'), ('当代', '当代')], default='唐', max_length=20, verbose_name='朝代')),
                ('content', models.TextField(verbose_name='诗词内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poetry.category', verbose_name='所属分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
            options={
                'verbose_name': '诗词',
                'verbose_name_plural': '诗词',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('appreciation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poetry.appreciation', verbose_name='所属赏析')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='poetry.comment', verbose_name='父评论')),
                ('poem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poetry.poem', verbose_name='所属诗词')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appreciation',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='poetry.poem', verbose_name='所属诗词'),
        ),
    ]
