# Generated by Django 4.2.7 on 2026-05-20 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('organizer', models.CharField(max_length=100, verbose_name='主办方')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('max_participants', models.IntegerField(default=50, verbose_name='最大人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前报名人数')),
                ('status', models.CharField(choices=[('upcoming', '即将开始'), ('ongoing', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='upcoming', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/', verbose_name='活动图片')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('student_id', models.CharField(max_length=50, verbose_name='学号')),
                ('college', models.CharField(max_length=100, verbose_name='学院')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'ordering': ['-registered_at'],
                'unique_together': {('activity', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='签到操作人')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.registration', verbose_name='报名记录')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
